CREATE DATABASE naodatabase;
use naodatabase;

CREATE TABLE inventario(
CODIGO int not null AUTO_INCREMENT PRIMARY KEY,
UBICACION VARCHAR(50) NOT NULL,
PRODUCTO VARCHAR(50) NOT NULL,
UNIDAD VARCHAR(50) NOT NULL,
CANTIDAD VARCHAR(50) NOT NULL,
COST_UNID VARCHAR(50) NOT NULL,
VALOR_INV VARCHAR(50) NOT NULL
)

select * from inventario;

